"""empty message

Revision ID: 0bb9dbeb0a11
Revises: 1c5a33bf2eb1
Create Date: 2022-01-27 11:46:03.679083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb9dbeb0a11'
down_revision = '1c5a33bf2eb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country', sa.String(), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(), nullable=True))
    op.add_column('users', sa.Column('district', sa.String(), nullable=True))
    op.add_column('users', sa.Column('village', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'village')
    op.drop_column('users', 'district')
    op.drop_column('users', 'city')
    op.drop_column('users', 'country')
    # ### end Alembic commands ###
