"""empty message

Revision ID: 84cc86bc9707
Revises: b913cf0d5c45
Create Date: 2022-01-28 10:38:25.712038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cc86bc9707'
down_revision = 'b913cf0d5c45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('income_notif', sa.Enum('on', 'off', name='incomenotif'), nullable=True))
    op.add_column('users', sa.Column('expense_notif', sa.Enum('on', 'off', name='expensenotif'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'expense_notif')
    op.drop_column('users', 'income_notif')
    # ### end Alembic commands ###
