"""empty message

Revision ID: 8e1bfed48dc1
Revises: 931aecd7bfb9
Create Date: 2022-01-27 15:18:24.459808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e1bfed48dc1'
down_revision = '931aecd7bfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suggestions', sa.Column('feedback', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suggestions', 'feedback')
    # ### end Alembic commands ###
