"""empty message

Revision ID: 931aecd7bfb9
Revises: b873a2e86abf
Create Date: 2022-01-27 15:16:08.519941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '931aecd7bfb9'
down_revision = 'b873a2e86abf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
